#####################################
# swarm에서 작동하는 docker-compose
#####################################
version: '3.8'

########################### SERVICES
services:
  wordpress:
    image: ghcr.io/hansanghyeon/wordpress-redis:5.8.2-php8.0-apache-redis
    networks:
      - traefik_proxy
      - default
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis */
        define('WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_HOST', 'redis'));
        define('WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', 6379));
    volumes:
      - ./apps/wp/wp-content:/var/www/html/wp-content
      - ./apps/wp/src:/var/www/html/wp-content/themes/headless
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.${TYPE}_${PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${TYPE}_${PROJECT_NAME}.rule=Host(`headless.${DOMAIN}`)
      - traefik.http.routers.${TYPE}_${PROJECT_NAME}.tls.certresolver=leresolver
      - traefik.http.services.${TYPE}_${PROJECT_NAME}.loadbalancer.server.port=80

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: wp
      MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./apps/wp/.db:/var/lib/mysql
  redis:
    image: redis:latest
    volumes:
      - redis:/data

  storybook:
    image: nginx
    networks:
      - traefik_proxy
      - default
    volumes:
      - ./packages/ui/storybook-static:/usr/share/nginx/html
      - ./.docker/storybook/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.${TYPE}_storybook_${PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${TYPE}_storybook_${PROJECT_NAME}.rule=Host(`storybook.${DOMAIN}`)
      - traefik.http.routers.${TYPE}_storybook_${PROJECT_NAME}.tls.certresolver=leresolver
      - traefik.http.services.${TYPE}_storybook_${PROJECT_NAME}.loadbalancer.server.port=80

########################### NETWORKS
networks:
  traefik_proxy:
    external: true

volumes:
  redis:
